apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-mcp-deployment
  namespace: default
  labels:
    app: sales-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-mcp
  template:
    metadata:
      labels:
        app: sales-mcp
    spec:
      containers:
      - name: sales-mcp-container
        image: knowbr/sales-mcp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
        env:
        # 1. Alimenta o GetConnectionString("ReadOnly") do C#
        - name: ConnectionStrings__ReadOnly
          valueFrom:
            secretKeyRef:
              name: mcp-database-secret
              key: connection-string
        
        # 2. Injeta a senha direto na memória (Ativa o Builder do C#)
        - name: Database__ReadOnlyPassword
          valueFrom:
            secretKeyRef:
              name: mcp-database-secret
              key: db-password

        # 3. Injeta o Token Bearer direto na memória (Ativa a nova lógica do FileTokenProvider)
        - name: McpOptions__BearerToken
          valueFrom:
            secretKeyRef:
              name: mcp-database-secret
              key: mcp-token

        # 4. Evita que a validação [Required] do DataAnnotations falhe ao iniciar o Host
        - name: McpOptions__BearerTokenFile
          value: "not-used-in-production"

      imagePullSecrets:
      - name: dockerhub-secret
