apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-mcp-deployment
  namespace: default # Ajustado com 2 espaços de recuo (dentro de metadata)
  labels:
    app: sales-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-mcp
  template:
    metadata:
      labels:
        app: sales-mcp
    spec:
      containers:
      - name: sales-mcp-container
        image: knowbr/sales-mcp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # Altere para a porta interna da sua aplicação, se necessário
        
        # Adicione este bloco abaixo para injetar as credenciais do banco:
        env:
        - name: ConnectionStrings__ReadOnly
          valueFrom:
            secretKeyRef:
              name: mcp-database-secret
              key: connection-string
              
        # Aponta para onde o Kubernetes vai montar o arquivo de texto com a senha
        - name: Database__ReadOnlyPasswordFile
          value: "/app/secrets/readonly-password.txt"

      
      # Corrigido o alinhamento para o nível da spec do Pod
      imagePullSecrets:
      - name: dockerhub-secret
